version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-browsers-legacy

    working_directory: ~/repo

    steps:

      - checkout

      - run: mvn dependency:go-offline

      - run: mvn package
